# Generated by Django 3.0.2 on 2020-03-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da venda')),
                ('cliente', models.CharField(max_length=60)),
                ('preco_total', models.FloatField(verbose_name='Preço total')),
                ('desconto', models.FloatField(verbose_name='Desconto Total')),
                ('pagamento', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit'), ('money', 'money'), ('nesp', 'nesp')], default='nesp', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RetiradaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.Venda')),
            ],
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor do produto')),
                ('data_alteracao', models.DateTimeField(verbose_name='Data da alteração')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.Produto')),
            ],
        ),
    ]
