# Generated by Django 3.0.2 on 2020-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiradaproduto',
            name='desconto',
            field=models.FloatField(default=0, verbose_name='Desconto no produto.'),
            preserve_default=False,
        ),
    ]
