# Generated by Django 3.0.2 on 2020-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_retiradaproduto_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='recebido',
            field=models.FloatField(default=0, verbose_name='Dinheiro recebido'),
            preserve_default=False,
        ),
    ]
